-- Soluciona el problema de not null 
ALTER TABLE IF EXISTS usuarios
ADD COLUMN rol VARCHAR(255) NOT NULL DEFAULT 'USER';

ALTER TABLE IF EXISTS proyectos
ADD COLUMN estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE';
