-- Agregar columnas de auditoría a la tabla USUARIOS
ALTER TABLE usuarios 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Agregar columnas de auditoría a la tabla PROYECTOS
ALTER TABLE proyectos 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Agregar columnas de auditoría a la tabla TAREAS
ALTER TABLE tareas 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Agregar columnas de auditoría a la tabla WORKSPACE
ALTER TABLE workspace 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Agregar columnas de auditoría a la tabla WORKSPACE_MEMBER
ALTER TABLE workspace_member 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;